name: newbase60
version: 0.1.0.0
github: "astralbijection/newbase60-hs"
license: MPL-2.0
author: "Astrid Yu"
maintainer: "astrid@astrid.tech"
copyright: "Astrid Yu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: Encodes and decodes numbers using Tantek Çelik's New Base 60 number system.
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/astralbijection/newbase60-hs#readme>

default-extensions:
  - LambdaCase
  - OverloadedStrings

dependencies:
  - base >= 4.14.1 && < 4.15
  - array >= 0.5.4 && < 0.6
library:
  source-dirs: src

tests:
  newbase60-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - newbase60
      - hspec
      - QuickCheck
      - bytestring
